# This is a basic workflow to help you get started with Actions

name: status test

# Controls when the action will run. 
on:
  status:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  on-status:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: payload
        run: cat $GITHUB_EVENT_PATH

      - name: GITHUB_REF
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}
